### ISSUE TITLE
SQLite DB not interpreting boolean field

### ISSUE THREAD

**Issue by kd-ods** [DataTig/DataTig#10]
If you download the DB file from the [org-id/datatig site](https://org-id-register.netlify.app/) and take a look at field_confirmed in the record_lists table, all the values for all lists are NULL. That's not correct.

**Comment by kd-ods** [comment]
@odscjames - how quick a fix might this be? I want to do a quick analysis of global coverage of org-id.

**Comment by odscjames** [comment]
https://github.com/org-id/register/pull/515 will fix this - code is already done
